import pytest


def test_service():
    #raise Exception('Exception generated')
    pass
